local opt = vim.opt

opt.number = true
opt.relativenumber = true
opt.tabstop = 2
opt.shiftwidth = 2
opt.expandtab = true
opt.smartindent = true
opt.clipboard = 'unnamedplus'
opt.list = true
opt.listchars = { tab = '»-', trail = '-', eol = '↲' }
opt.virtualedit = 'block'
opt.whichwrap = 'b,s,[,],<,>'
opt.backspace = { 'indent', 'eol', 'start' }
opt.wildmenu = true
opt.hidden = true
opt.history = 1000
opt.title = true
opt.scrolloff = 8
opt.signcolumn = 'yes'
opt.termguicolors = true
opt.wrap = true
opt.cursorline = true
opt.ignorecase = true
opt.smartcase = true
opt.splitright = true
opt.splitbelow = true
opt.updatetime = 250
opt.mouse = 'a'
opt.fileencoding = 'utf-8'
opt.swapfile = false
opt.backup = false
opt.undofile = true
opt.hlsearch = true
opt.incsearch = true
opt.showmode = false
opt.pumheight = 15
opt.conceallevel = 0
